---
- name: Download the installation script
  get_url:
    url: https://my-netdata.io/kickstart.sh
    dest: ~/kickstart.sh
    mode: +x
  register: netdata

- name: Install Netdata
  command: ~/kickstart.sh --dont-wait
  when: netdata.changed

- template:
    src: templates/netdata.conf.j2
    dest: /etc/netdata/netdata.conf
    owner: root
    group: root
    mode: u=wrx,g=rx,o=r,+x
  notify: Restart Netdata
  become: true

- name: Claim to Netdata Cloud
  block:
    - name: Check if node is already claimed
      # This check is used to prevent errors in the following task to claim the node to Netdata Cloud.
      stat:
        path: /var/lib/netdata/cloud.d/claimed_id
      register: claimed_result

    - name: Claim to Netdata Cloud
      shell: netdata-claim.sh -token={{ claim_token }} -rooms={{ claim_rooms }} -url={{ claim_url }}
      when: claimed_result.stat.exists == false
      become: yes
  when: reclaim == false

- name: Re-claim a node to Netdata Cloud
  block:
    - name: Ensure `uuidgen` is installed
      stat:
        path: /usr/bin/uuidgen
      register: uuidgen_result

    - name: Fail if `uuidgen` is not installed
      fail:
        msg: The system needs `uuidgen` installed to enable re-claiming.
      when: uuidgen_result.stat.exists == false

    - name: Reclaim the node with `-id=`
      shell: netdata-claim.sh -token={{ claim_token }} -rooms={{ claim_rooms }} -url={{ claim_url }} -id=$(uuidgen)
      when: uuidgen_result.stat.exists == true
      notify: Restart Netdata
      become: yes
  when: reclaim == true
