---
- name: Disable install check
  command:
    cmd: mv /var/www/bluespice/w/installcheck.php /var/www/bluespice/w/installcheck.php.disabled

- name: Set permission script
  template:
    src: templates/setWikiPerm.j2
    dest: /usr/local/bin/setWikiPerm
    mode: 1755

- name: Set bluespice configuration
  template:
    src: templates/LocalSettings.php.j2
    dest: /var/www/bluespice/w/LocalSettings.php

- name: Update bluespice
  command:
    cmd: php /var/www/bluespice/w/maintenance/update.php

- name: Update permissions
  command:
    cmd: setWikiPerm /var/www/bluespice/
