---
- name: Enable Elasticsearch
  ansible.builtin.systemd:
    state: started
    enabled: yes
    name: elasticsearch

- name: Reload Elasticsearch
  service:
    name: elasticsearch
    state: reloaded

- name: Restart Elasticsearch
  service:
    name: elasticsearch
    state: restarted
