---
- name: Download PhantomJS
  ansible.builtin.unarchive:
    remote_src: yes
    src: https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
    dest: /opt/
    owner: www-data

    mode: 1755

- name: Write PhantomJS configuration
  template:
    src: templates/090-PhantomJS.php.j2
    dest: /var/www/bluespice/w/settings.d/090-PhantomJS.php
