---
- name: Install Jetty9 Packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  loop: ["jetty9"]

- name: Configure Jetty9
  template:
    src: templates/jetty9.j2
    dest: /etc/default/jetty9
  notify: Restart jetty9

- name: Make sure jetty9 is running
  ansible.builtin.systemd:
    state: started
    enabled: yes
    name: jetty9

- name: Install latexrenderer
  copy:
    remote_src: yes
    src: /var/www/bluespice/w/extensions/BlueSpiceLatexRenderer/webservices/BSLaTeX2PNG.war
    dest: /var/lib/jetty9/webapps/
  notify: Restart jetty9

- name: Install Pdf Export
  copy:
    remote_src: yes
    src: /var/www/bluespice/w/extensions/BlueSpiceUEModulePDF/webservices/BShtml2PDF.war
    dest: /var/lib/jetty9/webapps/
  notify: Restart jetty9

- name: Install Visual Diff
  copy:
    remote_src: yes
    src: /var/www/bluespice/w/extensions/BlueSpiceVisualDiff/webservices/BShtmlDiff.war
    dest: /var/lib/jetty9/webapps/
  notify: Restart jetty9
