---
- name: Install MariaDb Packages
  apt: name={{ item }} update_cache=yes state=latest
  loop: ["mariadb-server", "mariadb-client"]

- name: Ensure mysql is running and starts on boot
  service:
    name: mysql
    state: started
    enabled: yes

- name: Install mysql python package
  pip:
    name: PyMySQL

- name: Update MariaDB root password
  community.mysql.mysql_user:
    check_implicit_admin: yes
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: "root"
    login_password: "{{ mysql_root_password }}"
    name: root
    host: "{{item}}"
    password: "{{mysql_root_password}}"
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

- name: Delete anonymous MySQL user
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: "root"
    login_password: "{{ mysql_root_password }}"
    name: ""
    host: "{{item}}"
    state: absent
  with_items:
    - localhost
    - "{{ansible_nodename}}"

- name: Delete Hostname based MySQL user
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: "root"
    login_password: "{{ mysql_root_password }}"
    name: root
    host: "{{ansible_nodename}}"
    state: absent

- name: Remove MySQL test database
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: "root"
    login_password: "{{ mysql_root_password }}"
    name: test
    state: absent

- name: Create bluespice database
  community.mysql.mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: "root"
    login_password: "{{ mysql_root_password }}"
    name: "{{db_name}}"
    state: present

- name: Create bluespice user
  community.mysql.mysql_user:
    login_user: "root"
    login_password: "{{ mysql_root_password }}"
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    login_host: "{{db_host}}"
    priv: "{{db_name}}.*:ALL,GRANT"
    state: present
