---
- name: Install Nodejs
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  loop: ["nodejs", "npm"]

- name: Git checkout
  ansible.builtin.git:
    repo: "https://gerrit.wikimedia.org/r/p/mediawiki/services/parsoid"
    dest: /opt/parsoid
    version: v0.10.0
    force: yes
    depth: 1
    single_branch: true

- name: Install parsoid
  community.general.npm:
    production: yes
    path: /opt/parsoid

- name: Move config
  copy:
    remote_src: yes
    src: /var/www/bluespice/w/extensions/BlueSpiceVisualEditorConnector/docs/parsoid/
    dest: /opt/parsoid
  register: parsoid

- name: Install pm2
  community.general.npm:
    production: yes
    global: yes
    name: pm2
  notify:
    - Add pm2 to startup

# - name: Write config file
#   template:
#     src: templates/config.yaml.j2
#     dest: /opt/parsoid/config.yaml
#     mode: "0644"
#     owner: www-data
#     group: www-data
#   register: parsoids

- name: Delete Parsoid via pm2
  command:
    cmd: pm2 delete server
    chdir: /opt/parsoid/
  when: parsoid.changed

- name: Start Parsoid via pm2
  command:
    cmd: pm2 start /opt/parsoid/bin/server.js
    chdir: /opt/parsoid/
  notify:
    - save pm2 config
  when: parsoid.changed
