---
- name: Configure open ports with ufw
  ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  with_items:
    - { rule: "allow", port: 22, proto: "tcp" }
    - { rule: "allow", port: 53, proto: "tcp" }
    - { rule: "allow", port: 53, proto: "udp" }
    - { rule: "allow", port: 80, proto: "tcp" }
    - { rule: "allow", port: 443, proto: "tcp" }

- name: configure default rules
  ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
    state: enabled
  with_items:
    - { direction: outgoing, policy: allow }
    - { direction: incoming, policy: deny }

- name: Install fail2ban
  apt:
    name: fail2ban
    state: present

- name: Ensure fail2ban is running
  service:
    name: fail2ban
    state: started
    enabled: yes
