---
- name: Move .war
  copy:
    remote_src: yes
    src: /var/www/bluespice/w/extensions/BlueSpiceLatexRenderer/webservices/BSLaTeX2PNG.war
    dest: /var/lib/jetty9/webapps/
  notify: Restart jetty9
