---
- name: Add php repository
  ansible.builtin.apt_repository:
    repo: ppa:ondrej/php

- name: Install PHP Packages
  apt: name={{ item }} update_cache=yes state=latest
  loop:
    [
      "apache2",
      "libapache2-mod-php7.3",
      "php7.3",
      "php7.3-cli",
      "php7.3-common",
      "php7.3-curl",
      "php7.3-gd",
      "php7.3-intl",
      "php7.3-json",
      "php7.3-mbstring",
      "php7.3-mysql",
      "php7.3-opcache",
      "php7.3-tidy",
      "php7.3-xml",
      "php7.3-zip",
      "php7.3-apcu",
      "git",
    ]

- name: Set php.ini
  template:
    src: templates/php.ini.j2
    dest: /etc/php/7.3/apache2/php.ini
